// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudSpeRece.Server.Data;

#nullable disable

namespace MudSpeRece.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MudSpeRece.Shared.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Checkbox")
                        .HasColumnType("int");

                    b.Property<int>("Checkbox1")
                        .HasColumnType("int");

                    b.Property<int>("Checkbox2")
                        .HasColumnType("int");

                    b.Property<int>("Checkbox3")
                        .HasColumnType("int");

                    b.Property<string>("Containa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.Property<int>("WorkDivisionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Receptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "いい仕事してますね",
                            Checkbox = 0,
                            Checkbox1 = 0,
                            Checkbox2 = 0,
                            Checkbox3 = 0,
                            Containa = "2M",
                            CreatedAt = new DateTime(2022, 10, 13, 11, 11, 55, 928, DateTimeKind.Local).AddTicks(8180),
                            CusName = "得意先商事",
                            RecDate = new DateTime(2022, 10, 13, 11, 11, 55, 928, DateTimeKind.Local).AddTicks(8148),
                            RecName = "金山昌弘",
                            RegName = "タイガー",
                            UpdatedAt = new DateTime(2022, 10, 13, 11, 11, 55, 928, DateTimeKind.Local).AddTicks(8182),
                            Userid = 3,
                            WorkDivisionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "いい仕事してますね2",
                            Checkbox = 0,
                            Checkbox1 = 0,
                            Checkbox2 = 0,
                            Checkbox3 = 0,
                            Containa = "3M",
                            CreatedAt = new DateTime(2022, 10, 13, 11, 11, 55, 928, DateTimeKind.Local).AddTicks(8191),
                            CusName = "得意先商事2",
                            RecDate = new DateTime(2022, 10, 13, 11, 11, 55, 928, DateTimeKind.Local).AddTicks(8186),
                            RecName = "金山昌弘2",
                            RegName = "タイガー2",
                            UpdatedAt = new DateTime(2022, 10, 13, 11, 11, 55, 928, DateTimeKind.Local).AddTicks(8192),
                            Userid = 4,
                            WorkDivisionId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
